# -*- coding: utf-8 -*-
"""
    Settings file for Eve.

    Different from a configuration file for an Eve application backed by
    Mongo as we need to define the schema using the registerSchema decorator.
"""
from eve.utils import config

from eve_sqlalchemy.decorators import registerSchema

from .tables import Invoices, People

ID_FIELD = 'id'
config.ID_FIELD = ID_FIELD
RESOURCE_METHODS = ['GET', 'POST']

# Need to be called *after* setting config.ID_FIELD
registerSchema('people')(People)
registerSchema('invoices')(Invoices)

SQLALCHEMY_DATABASE_URI = 'sqlite://'

# The following two lines will output the SQL statements executed by
# SQLAlchemy. This is useful while debugging and in development, but is turned
# off by default.
# --------
# SQLALCHEMY_ECHO = True
# SQLALCHEMY_RECORD_QUERIES = True

DEBUG = True

# The default schema is generated by the decorator
DOMAIN = {
    'people': People._eve_schema['people'],
    'invoices': Invoices._eve_schema['invoices']
}

# but you can always customize it:
DOMAIN['people'].update({
    'item_title': 'person',
    'additional_lookup': {
        'url': 'regex("[0-9]+")',
        'field': 'id'
    },
    'cache_control': 'max-age=10,must-revalidate',
    'cache_expires': 10,
    'resource_methods': ['GET', 'POST', 'DELETE']
})
